version: "3"
services:
  web:
    image: techtestapp:latest
    command: "/usr/app/startup.sh"
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOSTNAME=localhost
      - DB_NAME=servian
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:10.7
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
