apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme-app"
spec:
  selector:
    matchLabels:
      app: "acme-app"
  replicas: {{ .Values.replicaCount }}
  template: 
    metadata:
      labels:
        app: "acme-app"
    spec:
      containers:
      # - image: techtestapp:latest
      - image: {{ .Values.image }}
        name: "acme-app"
        env: 
          - name: TT_DBHOST
            value: {{ .Values.dbhost }}
        ports:
        - containerPort: 80